// bookmark_front/src/views/main/pages/personSpace/UserInfo.vue
<template>
  <div class="userInfo">
    <div class="icon">
      <img :src="userInfo.icon" class="full" />
      <label class="full">
        <input type="file" style="display: none" @change="changeIcon" />
        <div class="full changeIcon">
          <span>编辑</span>
        </div>
      </label>
    </div>
    <div class="baseInfo">
      <div class="item">

        <a-tooltip title="点击修改" v-if="currentAction!='name'">
          <span style="font-size:2em;cursor: pointer;" @click="()=>this.currentAction='name'">{{userInfo.username}}</span>
        </a-tooltip>
        <div class="inputGroup" v-else-if="currentAction==='name'">
          <a-input type="text" v-model="name" placeholder="修改昵称" />
          <div style="padding-top:0.2em">
            <a-button style="margin-right:2em" type="warn" @click="()=>this.currentAction=null">取消</a-button>
            <a-button type="primary" @click="submit">确定</a-button>
          </div>
        </div>
      </div>

      <div class="item">
        <span style="width:5em">密码</span>
        <a-tooltip title="点击修改" v-if="currentAction!='password'">
          <span style="cursor: pointer;" @click="()=>this.currentAction='password'">**********</span>
        </a-tooltip>
        <div class="inputGroup" v-else-if="currentAction==='password'">
          <a-input type="password" v-model="oldPassword" placeholder="旧密码" />
          <a-input type="password" v-model="password" placeholder="新密码" />
          <a-input type="password" v-model="rePassword" placeholder="重复新密码" />
          <div style="padding-top:0.2em">
            <a-button style="margin-right:2em" type="warn" @click="()=>this.currentAction=null">取消</a-button>
            <a-button type="primary" @click="submit">确定</a-button>
          </div>
        </div>
      </div>

      <div class="item">
        <span style="width:5em">邮箱</span>
        <a-tooltip title="点击修改" v-if="currentAction!='email'">
          <span style="cursor: pointer;" @click="()=>this.currentAction='email'">{{userInfo.email}}</span>
        </a-tooltip>
        <div class="inputGroup" v-else-if="currentAction==='email'">
          <a-input type="password" v-model="oldPassword" placeholder="旧密码" />
          <a-input type="email" v-model="email" placeholder="email" />
          <div style="padding-top:0.2em">
            <a-button style="margin-right:2em" type="warn" @click="()=>this.currentAction=null">取消</a-button>
            <a-button type="primary" @click="submit">确定</a-button>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";
import HttpUtil from "../../../../util/HttpUtil";
export default {
  name: "UserInfo",
  data() {
    return {
      currentAction: null, //当前操作,name,password,email
      name: "",
      oldPassword: "",
      password: "",
      rePassword: "",
      email: "",
    };
  },
  computed: {
    ...mapState("globalConfig", ["userInfo"]),
  },
  methods: {
    async changeIcon(e) {
      let file = e.target.files[0];
      if (!file || file.size > 200 * 1024) {
        message.error("文件大小请勿超过200KB");
        return;
      }
      let formData = new FormData();
      formData.append("file", file);
      let res = await HttpUtil.post("/user/icon", null, formData, true);
      this.$set(this.userInfo, "icon", res);
    },
    async submit() {
      let url, body;
      if (this.currentAction === "name") {
        url = "/baseInfo/username";
        body = { username: this.name };
      } else if (this.currentAction === "password") {
        if (!this.password === this.rePassword) {
          this.$message.error("新密码两次输入不一致");
          return;
        }
        url = "/baseInfo/password";
        body = {
          oldPassword: this.oldPassword,
          password: this.password,
        };
      } else {
        url = "/baseInfo/email";
        body = { oldPassword: this.oldPassword, email: this.email };
      }
      await HttpUtil.post(url, null, body);
      await this.$store.dispatch("globalConfig/refreshUserInfo");
      this.$message.success("操作成功");
      this.currentAction = null;
    },
  },
};
</script>

<style lang="less" scoped>
.userInfo {
  min-width: 50%;
  max-width: 30em;
  margin: 0 auto;
  display: flex;

  .icon {
    position: relative;
    border-radius: 5px;
    margin-right: 1em;
    cursor: pointer;
    @media (min-width: 768px) {
      width: 150px;
      height: 150px;
    }
    @media (max-width: 768px) {
      width: 75px;
      height: 75px;
    }

    .full {
      position: absolute;
      width: 100%;
      height: 100%;
    }

    .changeIcon {
      background-color: transparent;
      color: rgba(173, 166, 166, 0);
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 2em;
    }

    .changeIcon:hover {
      // background-color: rbga(173, 166, 166, 1);
      background-color: rgba(173, 166, 166, 0.8) !important;
      color: white;
    }
  }

  .item {
    font-size: 1.5em;
    padding-top: 1em;
    padding-bottom: 1em;
    border-bottom: 1px solid #ebebeb;

    display: flex;
    .inputGroup {
      flex: 1;
    }
  }

  .baseInfo {
    flex: 1;
  }
}
</style>

// front/src/pages/userSpace/components/UserInfo/index.jsx
import React from "react";
import { message, Button, Tooltip, Input, Form } from "antd";
import styles from "./index.module.less";
import { connect } from "react-redux";
import * as action from "../../../../redux/action/LoginInfoAction";
import httpUtil from "../../../../util/httpUtil";
import PasswordCheck from "../../../../components/PasswordCheck";

function mapStateToProps(state) {
  return state[action.DATA_NAME];
}

function mapDispatchToProps(dispatch) {
  return {
    updateOne: (key, value) => dispatch(action.updateOne(key, value))
  };
}

class UserInfo extends React.Component {
  constructor(props) {
    super(props);
    console.log(props);
    this.state = {
      email: null,
      isEmail: false,
      username: null,
      isUsername: false,
      password: "",
      repeatPassword: "",
      isPassword: false,
      actionId: null,
      isModelShow: false,
      //当前正在提交的
      currentAction: null,
      //当前正在提交的
      currentShowKey: null
    };
  }

  /**
   * 修改头像
   * @param {*} e
   */
  async changeIcon(e) {
    let file = e.target.files[0];
    if (!file || file.size > 500 * 1024) {
      message.error("文件大小请勿超过500KB");
      return;
    }
    let formData = new FormData();
    formData.append("file", file);
    let res = await httpUtil.post("/user/icon", formData, {
      headers: { "Content-Type": "multipart/form-data" }
    });
    console.log(res);
    this.props.updateOne("icon", res);
  }

  /**
   * 更新
   * @param {*} itemKey 修改的字段
   * @param {*} isShowKey 是否修改字段
   */
  async submit(itemKey, isShowKey) {
    if (this.state[itemKey] == null || this.state[itemKey] == "") {
      message.error("请修改后重试");
      return;
    }
    const { password, repeatPassword, actionId, email, username } = this.state;
    if (itemKey === "password" && password !== repeatPassword) {
      message.error("两次密码不一致");
      return;
    }
    if ((itemKey === "password" || itemKey === "email") && actionId == null) {
      message.warning("敏感操作，需校验密码");
      this.setState({ isModelShow: true, currentAction: itemKey, currentShowKey: isShowKey });
      return;
    }
    try {
      if (itemKey === "password") {
        await httpUtil.post("/baseInfo/password", { actionId, password });
        message.info("密码更新成功");
      } else if (itemKey === "email") {
        await httpUtil.post("/baseInfo/email", { actionId, email });
        this.props.updateOne("newEmail", email);
        message.info("新邮箱验证邮件已发送，请注意查收");
      } else {
        await httpUtil.post("/baseInfo/username", { username });
        this.props.updateOne("username", username);
      }
      this.setState({ [isShowKey]: false });
    } finally {
      this.setState({ actionId: null });
    }
  }

  async actionIdChange(actionId) {
    const { currentAction, currentShowKey } = this.state;
    this.setState({ actionId, isModelShow: false, currentAction: null, currentShowKey: null });
    this.submit(currentAction, currentShowKey);
  }

  /**
   * 渲染用户名
   * @param {string} itemKey
   * @param {string} isShowKey
   */
  renderItem(label, itemKey, isShowKey) {
    let repeatPassword = this.state.repeatPassword;
    let itemValue = this.state[itemKey] === null ? this.props[itemKey] : this.state[itemKey];
    let isShow = this.state[isShowKey];
    let block;
    if (isShow) {
      block = (
        <div>
          {itemKey == "password" ? (
            <div>
              <Input.Password value={itemValue} placeholder="新密码" onChange={e => this.setState({ [itemKey]: e.target.value })} />
              <Input.Password value={repeatPassword} placeholder="重复密码" onChange={e => this.setState({ repeatPassword: e.target.value })} />
            </div>
          ) : (
            <Input value={itemValue} onChange={e => this.setState({ [itemKey]: e.target.value })} />
          )}
          <div style={{ marginTop: "0.1rem" }}>
            <Button type="primary" onClick={this.submit.bind(this, itemKey, isShowKey)}>
              保存
            </Button>
            &nbsp;&nbsp;
            <Button onClick={() => this.setState({ [isShowKey]: false })}>取消</Button>
          </div>
        </div>
      );
    } else {
      block = (
        <Tooltip title="点击编辑">
          <div
            className={itemKey === "username" ? styles.username : "" + " pointer " + styles.value}
            onClick={() => this.setState({ [isShowKey]: true })}
          >
            {itemKey === "password" ? "********" : itemValue}
          </div>
        </Tooltip>
      );
    }
    return (
      <div className={styles.item + " flex"}>
        {label.length > 0 ? <div className={styles.label}>{label}</div> : null}
        {block}
      </div>
    );
  }

  render() {
    const { isModelShow } = this.state;
    const { icon, username } = this.props;
    return (
      <div className={styles.head}>
        {/* 头像昵称 */}
        <div className={styles.icon}>
          <img src={icon} alt="icon" className={styles.full} />
          <label className={styles.full}>
            <input type="file" style={{ display: "none" }} onChange={this.changeIcon.bind(this)} />
            <div className={styles.full + " " + styles.changeIcon}>
              <span>编辑</span>
            </div>
          </label>
        </div>
        {/* 个人信息 */}
        <div className={styles.userinfo}>
          {this.renderItem("", "username", "isUsername")}
          {this.renderItem("邮箱", "email", "isEmail")}
          {this.renderItem("密码", "password", "isPassword")}
        </div>

        <PasswordCheck visible={isModelShow} onClose={() => this.setState({ isModelShow: false })} onChange={this.actionIdChange.bind(this)} />
      </div>
    );
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(UserInfo);
